### ISSUE TITLE
Dreadlord suggestion.

### ISSUE THREAD

**Issue by Varus211** [Son-Guhun/Titan-Land-Lands-of-Plenty#16]
Allow Dreadlords to "Copy" a unit/heroes appearance/abilities. 
The ability can be used by the mimic and the imperial spy in KoT, both respective heroes.

**Comment by Son-Guhun** [comment]
Will do. I kinda of dislike these ability since it can't be seamlessly implemented (since the hero icons are not rearranged, so the order is messed up), but I guess it's not that big an issue.

**Comment by Son-Guhun** [comment]
Will be implemented as an item that any hero can use, since the ability itself is not that balanced. Item will be available in the Teleportation Solutions Shop, so that anyone can use it.

**Comment by Son-Guhun** [comment]
# To-do list:

- [ ] Implement Mimic library
- [ ] Implement Mimic ability
- [ ] Implement ability to return to normal form
- [ ] Create items (for mimic and for returning to normal form)
- [ ] Handle Mimic unit dying or being removed from the game (should show the original unit)
