### ISSUE TITLE
Get rid of the Mind power in favor of -give all

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/Titan-Land-Lands-of-Plenty#171]
With the addition of the -give command, the Mind power has become a relic of the past. Since players have already gotten used to LoP, it is no longer necessary as a compatibility feature for old TL maps.

# Tasks
- [x] Remove the Power: Mind unit
- [x] Remove the -mind command
- [x] Remove the 'mind command
- [x] Add a new -give all command
