### ISSUE TITLE
TO-DO List for Pathing Maps

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/Titan-Land-Lands-of-Plenty#202]
What needs to be handled:
- Default Models
- Custom Models
- Existing structures

## Default Models
- [x] Create script that reads doodad.ini and unit.ini to create a map from models to pathing textures
- [x] Create a script to map a unit to a pathing texture using its model

## Custom Models
- [x] Create a database that maps a derivative model to its base model.
- [x] Use pathing maps for base models on derivatives.
- [x] Handle custom models that aren't derivative.
  - [x] Create a command in-game to give generic pathing maps and check how each one fits
  - [x] Create a file that maps a unit to a generic pathing map

## Existing structures
- [x] Create a json file for legacy structures that maps unit ids to pathing maps
- [x] For structures that use default pathing maps, simply use those.
- [x] For structures that use custom pathing maps, integrate those with imagereader.py
- [x] Convert all structures to units

# Check which decorations are still missing a pathing map
- [x] Create a file that lists all decorations that should not have a pathing map.
- [x] Decorations with missing pathing maps that aren't in that list are reported.
