### ISSUE TITLE
Add -roll command

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/Titan-Land-Lands-of-Plenty#21]
## Syntax

Max dice number (not sides): 100 (so you can't do 101d100, but you can do 100d101)

Tabletop:
-roll 2d6 = > Rolls 2d6
-roll 2d6 + 10 => Rolls 2d6 and adds 10 to the result

Range:
-roll 10 => Random number between 1 and 10 (equivalent to 1d10)
-roll 10 20 => Random number between 10 and 20 (equivalent to 1d10 + 9)
-roll 3 10 20 => Sum of 3 random numbers between 10 and 20 (equivalent to 3d10 + 27)

## To-do
- [x] Implement command
- [x] Implement tabletop syntax
- [x] Implement range syntax
- [x] Implement showing individual die results for up to 5 dice
