### ISSUE TITLE
v.1.5.0-beta1 checklist

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/Titan-Land-Lands-of-Plenty#212]
- [ ] Hint when entering fullscreen mode so people can know how to deactivate it.
- [ ] Exit button for tools menu
- [ ] Exit button for deco browser
- [ ] Help button for deco browser
- [ ] Get FPS and PING commands to work again
- [ ] Hide pathing maps
- [ ] Elapsed time should be visible by default. Add button mechanic on day-time clock to hide it.
- [ ] Close issue #204
- [ ] Close issue #176
- [ ] Close issue #189
