### ISSUE TITLE
Remove Limit System and increase default Load Limit

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/Titan-Land-Lands-of-Plenty#75]
- Limit system is simply not used. Every game the Titan sets the limits to really high numbers.
- Limit system may be causing crashes (no real evidence for this, but unit removal seems to cause crashes, so it might be the culprit). Since it's not ever used, there is no point in its existance and no harm done in removing it.
- Default load limit should be unlimitedn(MAX_INT), and the command can be used to limit the number of units that can be loaded.

## Tasks
- [x] Delete Register and Type change triggers in Map System category
- [x] Remove PlayerUnitLimit library and all references to its API
- [x] Increase the default load limit to 2147483647
